CREATE TABLE USERS(
USERNO number primary key,
EMAIL varchar2(500),
USERID varchar2(500),
PASSWORD varchar2(500)
)
CREATE SEQUENCE user_seq;

CREATE TABLE TODO(
TODONO number primary key,
TODO varchar2(1000),
TODODATE varchar2(500),
TODOCOMPL varchar2(10),
USERNO number,
CONSTRAINT TODO_FK_USERNO FOREIGN KEY(USERNO) REFERENCES USERS(USERNO)
)

CREATE SEQUENCE todo_seq;